### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Zont1k**
added information about downloading packages and an example code for starting the bot

### CODE REVIEW

**Comment by csmir** [comment]
Why sample here, and not in the docs? I already pr'ed discord widget and it was preferred to be moved down to a full widget below...

**Comment by Zont1k** [comment]
I don't see a problem with having a sample here

**Comment by KubaZ2** [comment]
I think that package versions shouldn't be hardcoded. Additionally, installation process is described in the documentation. But hm, maybe it should be added here too.

The example you provided doesn't seem valid to me. `CommandService<CommandContext>` is created but never used. Also I am not sure if we should add code examples to readme. Examples take a lot of space.

**Comment by Zont1k** [comment]
Okay, you can remove the sample code and leave the nuget packages to install

**Comment by KubaZ2** [comment]
I think the installation instructions are provided on nuget.org and in the docs, so this is just duplication. I don't think it should be added here. Also, I think the instructions you provided only work in the VS package manager console.

**Pull request closed without merging**
